var MW = MW || {};
var winSize = cc.director.getWinSize();

//score
MW.SCORE = 0;
MW.HIGH_SCORE = 500;

//sound
MW.SOUND = true;

//container
MW.CONTAINER = {
    CACTI: [],
    BIRDS:[],
    BACKGROUND: [],
    CLOUDS: [],
    ROADS: []
};

MW.CACTUS_TYPE_DEFAULT = "single"

MW.DINO_STATUS = {
    CRASHED: 'CRASHED',
    DUCKING: 'DUCKING',
    JUMPING: 'JUMPING',
    RUNNING: 'RUNNING',
    WAITING: 'WAITING'
};

MW.INITIAL_SPEED = 500
MW.SPEED_INCREASE_RATE = 10
MW.SPEED_MAX = 1000

MW.GRAVITY = -4000
MW.JUMP_INIT_VELOCITY = 1250
MW.DROP_VELOCITY = -3000

MW.OBSTACLE_DIST = 100

MW.APPEAR_POSITION = [100, winSize.height/3]
MW.MIN_CLOUD_HEIGHT = 100
MW.MAX_CLOUD_HEIGHT = 100

